export const itemList = {
  basic: [
    "planks",
    "stick",
    "torch",
    "workbench",
    "chest",
    "furnace",
    "ladder",
    "fence",
    "boat",
    "wooden slabs",
    "stone slabs",
    "sign",
    "doors",
    "painting",
    "bed",
    "wood",
  ],
  blocks: [
    "glowstone",
    "snow block",
    "stone brick",
    "brick",
    "sandstone",
    "smooth sandstone",
    "decorative sandstone",
    "gold block",
    "diamond block",
    "iron block",
    "lapis lazuli block",
    "emerald block",
    "coal block",
    "wool block",
    "bookshelf",
    "note block",
    "clay block",
    "jack-o-lantern",
    "tnt",
    "wooden stairs",
    "stone stairs",
    "cobblestone walls",
    "block of redstone",
    "nether brick",
    "red nether brick",
    "chiseled nether bricks",
    "nether wart block",
    "block of quartz",
    "chiseled quartz block",
    "pillar quartz block",
    "quartz bricks",
    "hay bale",
    "stained clay",
    "stained glass",
    "granite",
    "andesite",
    "diorite",
    "polished granite",
    "polished andesite",
    "polished diorite",
    "prismarine",
    "prismarine bricks",
    "dark prismarine",
    "sea lantern",
    "coarse dirt",
    "slime block",
    "moss stone",
    "mossy stone brick",
    "chiseled stone brick",
    "red sandstone",
    "smooth red sandstone",
    "chiseled red sandstone",
    "purpur block",
    "purpur pillar",
    "magma block",
    "bone block",
    "dried kelp block",
    "packed ice",
    "blue ice",
    "honey block",
    "honeycomb block",
    "stripped wood",
    "polished basalt",
    "polished blackstone",
    "chiseled polished blackstone",
    "polished blackstone bricks",
    "block of netherite",
  ],
  defence: [
    "helmets",
    "chestplates",
    "leggings",
    "boots",
    "swords",
    "bow",
    "arrow",
    "horse armor",
    "shield",
    "spectral arrow",
    "tipped arrow",
    "conduit",
    "turtle shell",
    "crossbow",
  ],
  tools: [
    "pickaxes",
    "shovels",
    "axes",
    "hoes",
    "fishing rod",
    "flint and steel",
    "shears",
    "bucket",
    "clock",
    "compass",
    "map",
    "shulker box",
  ],
  food: [
    "cake",
    "bread",
    "cookie",
    "bowl",
    "mushroom stew",
    "golden apple",
    "pumpkin seeds",
    "melon seeds",
    "melon block",
    "sugar",
    "golden carrot",
    "pumpkin pie",
    "rabbit stew",
    "suspicious stew",
    "honey bottle",
  ],
  mechanism: [
    "pressure plates",
    "weighted pressure plates",
    "lever",
    "buttons",
    "trapdoor",
    "piston",
    "sticky piston",
    "fence gate",
    "redstone repeater",
    "dispenser",
    "jukebox",
    "minecart",
    "powered minecart",
    "storage minecart",
    "track",
    "powered rail",
    "detector rail",
    "activator rail",
    "redstone torch",
    "redstone lamp",
    "tripwire hook",
    "daylight sensor",
    "dropper",
    "hopper",
    "minecart with hopper",
    "minecart with TNT",
    "redstone comparator",
    "trapped chest",
    "iron trapdoor",
    "observer",
    "target",
  ],
  brewing: [
    "glass bottle",
    "cauldron",
    "brewing stand",
    "glistering melon",
    "blaze powder",
    "fermented spider eye",
    "magma cream",
  ],
  other: [
    "paper",
    "book",
    "book and quill",
    "iron bars",
    "nether brick fence",
    "gold ingot",
    "eye of ender",
    "enchantment table",
    "fire charge",
    "ender chest",
    "beacon",
    "anvil",
    "flower pot",
    "item frame",
    "carrot on a stick",
    "firework rocket",
    "firework star",
    "lead",
    "carpets",
    "glass panes",
    "leather",
    "banner",
    "armor stand",
    "end rod",
    "end crystal",
    "iron nugget",
    "concrete powder",
    "campfire",
    "soul campfire",
    "scaffolding",
    "barrel",
    "blast furnace",
    "smoker",
    "cartography table",
    "composter",
    "fletching table",
    "smithing table",
    "stonecutter",
    "grindstone",
    "lanterns",
    "lectern",
    "loom",
    "beehive",
    "chain",
    "netherite ingot",
    "soul torch",
    "respawn anchor",
    "lodestone",
  ],
  dye: [
    "red dye",
    "yellow dye",
    "cyan dye",
    "pink dye",
    "purple dye",
    "magenta dye",
    "lime dye",
    "light blue dye",
    "orange dye",
    "light gray dye",
    "gray dye",
    "bone meal",
    "white dye",
    "blue dye",
    "brown dye",
    "black dye",
  ],
  wool: [
    "light gray wool",
    "pink wool",
    "lime wool",
    "red wool",
    "green wool",
    "black wool",
    "purple wool",
    "blue wool",
    "orange wool",
    "brown wool",
    "yellow wool",
    "cyan wool",
    "light blue wool",
    "magenta wool",
    "gray wool",
  ],
};
